Feature/seunghojeong
wecode-bootcamp-korea/13-grafolWEo-backend pull request #1
Opened 2020-10-21 10:56 UTC by Dan-Jeong

>wecode PR message template 및 체크 리스트 입니다.
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 및 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
- user App. 생성
회원관리 DB용 Models.py 작성
urls.py 내 회원가입, 로그인 엔드포인트 생성
views.py 내 회원가입, 로그인(token 생성포함) 코드 작성
- settings.py 파일 설정
- .gitignore 신규작성

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-10-21 13:23 UTC, soheon-lee commented
@Dan-Jeong 승호님 현재 models.py 만 merge가능할 것 같아서 views.py에 있는 코드는 잠깐 다른 곳에 백업해두고, 파일 내용 지우고 올려주세요~

2020-10-22 09:22 UTC, lordmyshepherd requested changes

2020-10-22 09:22 UTC, lordmyshepherd commented on work/models.py
> +    image_url       = models.CharField(max_length = 1000)
URLField를 사용해보시면 어떨까요?

2020-10-22 09:22 UTC, lordmyshepherd commented on work/models.py
> +    category        = models.ManyToManyField(Category, through = "CategoryToTag", related_name = "categories")
many to many field는 tag 보다는 category 쪽에 위치하는게 좋습니다.
이유는 category에서 연관된 tag를 조회하는 경우가, tag에서 category를 조회하는 경우보다 많을 것으로 예상되기 때문입니다~

2020-10-22 09:22 UTC, lordmyshepherd commented on work/models.py
> +    work            = models.ManyToManyField(Work, through = "WorkToTag", related_name = "works")
마찬가지 입니다~

2020-10-22 09:31 UTC, lordmyshepherd requested changes

2020-10-22 09:31 UTC, lordmyshepherd commented on user/models.py
> +    following           = models.ManyToManyField(
아래 코드를 참고해서 수정해 보시겠어요?
```
class User(models.Model):
    korean_name       = models.CharField(max_length=45) 
    password          = models.CharField(max_length=200)
    friends           = models.ManyToManyField('self', through='Friend', related_name='followers', symmetrical=False)

    class Meta:
        db_table = 'users'

class Friend(models.Model):
    from_user = models.ForeignKey('User', on_delete=models.CASCADE, related_name='to_user')
    to_user   = models.ForeignKey('User', on_delete=models.CASCADE, related_name='from_user')

   class Meta:
        unique_together = ('from_user', 'to_user')
        db_table        = 'friends'
```

2020-10-22 12:13 UTC, Dan-Jeong commented on user/models.py
> +    following           = models.ManyToManyField(
Question.
리뷰 주신 내용을 참고하여 Unique_together에 대해서 Goolging해보았습니다.
Unique_together가 ManyToMany 중간 테이블의 Field 조합의 고유성을 확보하기 위해 사용하는 것 같은데
이것이 어떤 경우를 대비하여 사용하는지 쉽게 이해되지 않습니다.
그렇다면 자기참조가 아닌 일반적인 M-to-M 관계의 경우에도 많은 데이터를 처리한 다는 가정하에 동일한 옵션을 주어야 하는지요.

2020-10-22 12:13 UTC, Dan-Jeong commented on work/models.py
> +    image_url       = models.CharField(max_length = 1000)
리뷰 코멘트 반영하여 코드 수정하였습니다.

2020-10-22 12:14 UTC, Dan-Jeong commented on work/models.py
> +    category        = models.ManyToManyField(Category, through = "CategoryToTag", related_name = "categories")
보다 주체가 되는 쪽에 ManyToMany 필드를 넣어주었습니다.

2020-10-22 12:15 UTC, Dan-Jeong commented on work/models.py
> +    work            = models.ManyToManyField(Work, through = "WorkToTag", related_name = "works")
보다 주체가 되는 쪽에 ManyToMany 필드를 넣어주었습니다.

2020-10-22 12:27 UTC, soheon-lee commented on user/models.py
> +    following           = models.ManyToManyField(
일반적인 M-to-M 필드에서도 그 조합이 고유해야하는 경우에는 해당 옵션을 줄 수 있습니다 :)

2020-10-22 12:27 UTC, soheon-lee commented on work/models.py
> +
불필요한 간격은 삭제해주세요

2020-10-22 12:35 UTC, soheon-lee commented
@Dan-Jeong 아 그리고 브랜치 이름은 기능 단위로 작성합니다 :) 이후 부터는 이름 말고 기능 단위로 올려주세요~

2020-10-22 13:29 UTC, Dan-Jeong commented on work/models.py
> +
클래스별 필드명 띄어쓰기 적절한 간격으로 수정하였습니다.

2020-10-22 13:44 UTC, lordmyshepherd commented
LGTM 👍

2020-10-22 13:44 UTC, merged